// <auto-generated />
namespace Movies.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class addstudio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstudio));
        
        string IMigrationMetadata.Id
        {
            get { return "201309251742114_add-studio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
